
package epicerie;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Epicerie", targetNamespace = "http://epicerie/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Epicerie {


    /**
     * 
     * @param produit
     */
    @WebMethod
    public void enregister(
        @WebParam(name = "produit", partName = "produit")
        Produit produit);

    /**
     * 
     * @param idProduit
     * @param qte
     */
    @WebMethod
    public void ajouter(
        @WebParam(name = "idProduit", partName = "idProduit")
        Object idProduit,
        @WebParam(name = "qte", partName = "qte")
        int qte);

    /**
     * 
     * @param idProduit
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int obtenirQuantite(
        @WebParam(name = "idProduit", partName = "idProduit")
        Object idProduit);

    /**
     * 
     * @return
     *     returns epicerie.ListeProduit
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListeProduit listeProduits();

    /**
     * 
     * @return
     *     returns epicerie.ListeStock
     */
    @WebMethod
    @WebResult(partName = "return")
    public ListeStock listeStock();

}
